version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/var/www

  app-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
     - "9001:80"
    volumes:
    - ./:/var/www
    depends_on:
      - app
  
